apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: tms-min-side-utbetalingsoversikt
  namespace: min-side
  labels:
    team: min-side
spec:
  envFrom:
    - secret: tms-min-side-utbetalingsoversikt-secrets
  image: {{version}}
  port: 7400
  liveness:
    path: /tms-min-side-utbetalingsoversikt/internal/isAlive
    initialDelay: 10
  readiness:
    path: /tms-min-side-utbetalingsoversikt/internal/isReady
    initialDelay: 10
  replicas:
    min: 2
    max: 4
  ingresses:
    - "https://person.intern.nav.no/tms-min-side-utbetalingsoversikt"
  resources:
    limits:
      cpu: "3"
      memory: 768Mi
    requests:
      cpu: "50m"
      memory: 256Mi
